Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -11,8 +11,8 @@ on:
       domain:
         description: 'URL of the Website'
         required: true
-      domains:  # Consolidated the second and third domain as a single input
-        description: 'Comma-separated list of additional domains (e.g. files.example.com,api.example.com)'
+      second_domain:
+        description: 'Second domain (for example files subdomain)'
       app_name:
         description: 'Name of the App'
         required: true
@@ -34,23 +34,15 @@ on:
           - 'PORTRAIT'
           - 'LANDSCAPE'
       icon_url:
-        description: 'Icon URL (optional)'
+        description: 'Icon URL'
+      startup_url:
+        description: 'Start URL'
       no_ssl:
         description: 'No SSL - Not recommended!!'
         type: boolean
         default: false
 
 jobs:
-  id:
-    name: Workflow ID Provider
-    runs-on: ubuntu-latest
-    steps:
-      - name: Print Run Identifier
-        run: |
-          echo "Run identifier: ${{ github.event.inputs.id }}"
-
-
-
   build:
     runs-on: ubuntu-latest
     steps:
@@ -61,36 +53,34 @@ jobs:
         run: |
           validate_domain() {
             DOMAIN="${1}"
-          
-          # Remove protocol from URL if present
-          DOMAIN="${DOMAIN#http://}"
-          DOMAIN="${DOMAIN#https://}"
-          DOMAIN="${DOMAIN%%/*}"
-          
-          if ! [[ $DOMAIN =~ ^[A-Za-z0-9.-]+\.[A-Za-z0-9-]{2,}$ ]]; then
-            echo "Error: Invalid domain format: $DOMAIN"
-            exit 1
+            
+            # Remove protocol from URL if present
+            DOMAIN="${DOMAIN#http://}"
+            DOMAIN="${DOMAIN#https://}"
+            DOMAIN="${DOMAIN%%/*}"
+            
+            if ! [[ $DOMAIN =~ ^[A-Za-z0-9.-]+\.[A-Za-z0-9-]{2,}$ ]]; then
+              echo "Error: Invalid domain format: $DOMAIN"
+              exit 1
+            fi
+            echo $DOMAIN
+          }
+
+          # Validate and format primary domain
+          DOMAIN=$(validate_domain "${{ inputs.domain }}")
+          echo "PRIMARY_DOMAIN=$DOMAIN" >> $GITHUB_ENV
+          ALLOWED_DOMAINS="$DOMAIN"
+
+          # Validate and add additional domains if provided
+          if [ -n "${{ inputs.second_domain }}" ]; then
+            IFS=',' read -ra DOMAIN_ARRAY <<< "${{ inputs.second_domain }}"
+            for domain in "${DOMAIN_ARRAY[@]}"; do
+              VALIDATED_DOMAIN=$(validate_domain "$domain")
+              ALLOWED_DOMAINS="$ALLOWED_DOMAINS,$VALIDATED_DOMAIN"
+            done
           fi
-          echo $DOMAIN
-        }
 
-        # Validate and format primary domain
-        DOMAIN=$(validate_domain "${{ inputs.domain }}")
-        echo "PRIMARY_DOMAIN=$DOMAIN" >> $GITHUB_ENV
-        ALLOWED_DOMAINS="$DOMAIN"
-
-        # Validate and add additional domains if provided
-        if [ -n "${{ inputs.second_domain }}" ]; then
-          IFS=',' read -ra DOMAIN_ARRAY <<< "${{ inputs.second_domain }}"
-          for domain in "${DOMAIN_ARRAY[@]}"; do
-            VALIDATED_DOMAIN=$(validate_domain "$domain")
-            ALLOWED_DOMAINS="$ALLOWED_DOMAINS,$VALIDATED_DOMAIN"
-          done
-        fi
-
-        echo "ALLOWED_DOMAINS=$ALLOWED_DOMAINS" >> $GITHUB_ENV
-
-
+          echo "ALLOWED_DOMAINS=$ALLOWED_DOMAINS" >> $GITHUB_ENV
 
       - name: Validate app_name input
         run: |
@@ -152,3 +142,29 @@ jobs:
 
       - name: Rename APK
         run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/webview-${{ env.PRIMARY_DOMAIN }}.apk
+
+      - name: Create Release
+        id: create_release
+        uses: softprops/action-gh-release@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: v${{ github.run_id }}
+          name: Release v${{ github.run_id }} (${{ env.PRIMARY_DOMAIN }})
+          prerelease: true
+          draft: false
+          files: app/build/outputs/apk/release/webview-${{ env.PRIMARY_DOMAIN }}.apk
+          body: |
+            Restricted WebView App.
+            Domain: [${{ env.PRIMARY_DOMAIN }}](//${{ env.PRIMARY_DOMAIN }})
+            Second Domain: [${{ env.SECOND_DOMAIN }}](//${{ env.SECOND_DOMAIN }})
+            No Secured: ${{ inputs.no_ssl }}
+            App Name: ${{ inputs.app_name }}
+            View Mode: ${{ inputs.view_mode }}
+            Block Media: ${{ inputs.block_media }}
+            Block Ads: ${{ inputs.block_ads }}
+            Custom Icon: ${{ inputs.icon_url }}
+
+      - name: Get the APK URL
+        run: |
+          echo "APK URL: ${{ fromJSON(steps.create_release.outputs.assets)[0].browser_download_url }}"
